### ISSUE TITLE
Could not find a valid gem 'termin_de' (>= 0) in any repository

### ISSUE THREAD

**Issue by msdundar** [Strech/termin_de#11]
After running `gem install termin_de`as described in the README, I receive the following error:

```
ERROR:  Could not find a valid gem 'termin_de' (>= 0) in any repository
```

Indeed, I can't also find the gem in RubyGems.org.

**Comment by Strech** [comment]
Hey @msdundar this is a default new gem README, nothing much changed and the gem is not published since it's better to have a CLI.

I have some ideas around that and probably will rewrite it / or replace with something better soon™
