### ISSUE TITLE
[feature] Allow specify the burgermat ID

### ISSUE THREAD

**Issue by luizkowalski** [Strech/termin_de#7]
As the title says, would be nice if we could also specify the burgeramt ID

**Comment by Strech** [comment]
Hey, @luizkowalski thanks for the feature request. I'm open to any help with this small project 👋🏼

**Comment by luizkowalski** [comment]
@Strech I will try to code something then. also, do you happen to know the _exact_ rate limit setup by them? to me it looks like 60 seconds is a bit too much but I know that 2 seconds would cause issues so I'm trying to get that exact number

**Comment by Strech** [comment]
> do you happen to know the exact rate limit setup by them

Unfortunately no. When I was running it locally (back in the days) seems that once they block you you have this cooldown period (which is fixed) and then you can query them again. I tried exponential back-off for the timeout but 60 seconds works best and always succeed at the end
